import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'models/jsonmodel.dart';

class First_example extends StatefulWidget {
  const First_example({super.key});

  @override
  State<First_example> createState() => _First_exampleState();
}

class _First_exampleState extends State<First_example> {
  List<Autogenerated> postList = [];

  Future<List<Autogenerated>> getPostApi() async {
    final resposne = await http.get(
      Uri.parse('https://jsonplaceholder.typicode.com/posts'),
    );
    var data = jsonDecode(
      resposne.body.toString(),
    );
    if (resposne.statusCode == 200) {
      postList.clear();
      for (Map<String, dynamic> i in data) {
        postList.add(
          Autogenerated.fromJson(i),
        );
      }
      return postList;
    } else {
      return postList;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text('Api Course'),
        foregroundColor: Colors.black,
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: Column(
        children: [
          Expanded(
            child: FutureBuilder(
              future: getPostApi(),
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return Text('Loading');
                } else {
                  return ListView.builder(
                    itemCount: postList.length,
                    itemBuilder: (context, index) {
                      return Card(
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                            const  Text(
                                'Title',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                             const SizedBox(
                                height: 3,
                              ),
                              Text(postList[index].title.toString()),
                             const SizedBox(
                                height: 5,
                              ),
                             const Text(
                                'Description',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            const  SizedBox(
                                height: 3,
                              ),
                              Text(
                                'Description\n' +
                                    postList[index].body.toString(),
                                style: Theme.of(context).textTheme.bodySmall,
                              ),
                             const Text('Id is'),
                              Text(postList[index].userId.toString() +
                                  postList[index].id.toString())
                            ],
                          ),
                        ),
                      );
                    },
                  );
                }
              },
            ),
          )
        ],
      ),
    );
  }
}
